services:
  database:
    image: postgres
    container_name: postgres_container
    ports:
      - 5001:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=dbname

  viewland:
    image: viewland
    container_name: viewland_container
    build: .
    volumes:
      - ./data:/user_data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=dbname   
      - POSTGRES_HOST=postgres_container
      - POSTGRES_PORT=5432
    depends_on:
      - database

      