services:
  db:
    image: postgres
    container_name: postgres_container
    volumes:
      - ./database/db:/var/lib/postgresql/data
    ports:
      - 5001:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=dbname

  web:
    image: web_image
    container_name: web_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=dbname   
      - POSTGRES_HOST=postgres_container
      - POSTGRES_PORT=5432
    depends_on:
      - db

      
